[supervisord]
nodaemon = true
user = XXX
pidfile = /tmp/supervisord.pid
logfile = /tmp/supervisord.log

[program:jupyterlab]
environment=HOME="/home/XXX",USER="XXX",SHELL="/bin/bash"
directory = /home/XXX/warpx-tutorials/episodes/files
redirect_stderr = true
stdout_logfile = /var/log/jupyter.log
command = /opt/conda/envs/warpx/bin/jupyter lab --no-browser --ServerApp.ip=0.0.0.0 --ServerApp.port=3000 --ServerApp.root_dir=/home/XXX/warpx-tutorials/episodes --IdentityProvider.token="" --ServerApp.password="" --ServerApp.allow_origin="*" --ServerApp.allow_remote_access=True --ServerApp.disable_check_xsrf=True
